import type { Metadata } from "next";
import { Poppins, Geist_Mono } from "next/font/google";
// import localFont from "next/font/local";
import "./globals.css";
import HeroPage from './hero/page'
import Footer from "@/components/Footer";
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100' , '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900'],
  display: 'swap'
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const advanced_pixel_lcd = localFont({
//   src: [
//     {
//       path: "../public/fonts/advanced_pixel/advanced_pixel_lcd-7.ttf",
//       weight: "400",
//       style: "normal",
//     },
//   ],
//   variable: "--font-advanced-pixel-lcd",
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.cdnfonts.com/css/marlos" rel="stylesheet"></link>
      </head>
      <body
        className={`${poppins.variable} ${geistMono.variable} antialiased`}
      >
        <HeroPage/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
